StuffFinderApp/config/routes.rb
Rails.application.routes.draw do
  resources :categories, :classifieds, :users
  root 'classifieds#index'

end

StuffFinderApp/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :classifieds
end

StuffFinderApp/app/models/classified.rb
class Classified < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
end

StuffFinderApp/app/models/user.rb
class User < ActiveRecord::Base
	has_many :classifieds
end

StuffFinderApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

StuffFinderApp/app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController

  def index
    @classifieds = Classified.all
  end

  def show
    @classified = Classified.find(params[:id])
  end

  def new
    @classified = Classified.new
  end

  def create
    @classified = Classified.new classified_params

    if @classified.save
      redirect_to @classified
    else
      render 'new'
    end
  end

  private
    def classified_params
      params.require(:classified).permit(:title, :description, :price, :category_id)
    end
end

StuffFinderApp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

StuffFinderApp/app/helpers/application_helper.rb
module ApplicationHelper
end

StuffFinderApp/app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

StuffFinderApp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

StuffFinderApp/app/views/classifieds/index.html.erb
<h1>Classifieds</h1>

<h1>StuffFinder</h1>
<ul>
  <li>Classifieds</li>
  <li>New Classified</li>
  <li>Sign up</li>
  <li>Sign in</li>
</ul>

<div>
  <h1>Your place for finding stuff you want, and dumping stuff you don't</h1>
  <button><%= link_to 'Create a new classified!', new_classified_path(@classified) %></button>
  <button><%= link_to 'See our current classifieds', classifieds_path %></button>
</div>

StuffFinderApp/app/views/classifieds/new.html.erb
<h1>Add a classified</h1>

<%= form_for @classified do |f| %>

  <p>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </p>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

StuffFinderApp/app/views/classifieds/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @classified.title %> - <%= number_to_currency(@classified.price) %>
</p>

<p>
  <strong>Text:</strong>
  <%= @classified.description %>
</p>


<%= link_to 'Edit', edit_classified_path(@classified) %> | 
<%= link_to 'Back', classifieds_path %>

StuffFinderApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuffFinderApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

StuffFinderApp/app/views/welcome/index.html.erb
<h1>StuffFinder</h1>
<ul>
  <li>Classifieds</li>
  <li>New Classified</li>
  <li>Sign up</li>
  <li>Sign in</li>
</ul>

<div>
  <h1>Your place for finding stuff you want, and dumping stuff you don't</h1>
  <button><%= link_to 'Create a new classified!', new_classified_path(@classified) %></button>
  <button><%= link_to 'See our current classifieds', classifieds_path %></button>
</div>